<!DOCTYPE html>
<html>
<head>
	<title>Report</title>
	<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: center;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: rgb(240, 242, 242);
}
</style>
</head>
<body>
	<center>
		<h1 style="color: rgb(87, 92, 92);">Govt of Gujarat</h1>
		<h2 style="color: rgb(87, 92, 92);">Department of Road Maintainance</h2>
		<hr>
		<p style="color: rgb(87, 92, 92);">Report Generated By CE</p>
	 <table>
	 <tr style="background-color: rgba(3, 182, 252,0.5);color: white;">
	 	<th>ID</th>
	 	<th>state</th>
	 	<th>district</th> 
	 	<th>City Or Village</th>
	 	<th>Road Number</th>
	 	<th>Road Name</th>
	 	<th>RoadSize Length</th>
	 	<th>RoadSize Breadth</th>
	 	<th>Total Estimation Cost</th>
	 	<th>DamageLevel</th>
	 	<th>Mazon count</th>
	 	<th>Mazon cost</th>
	 	<th>Mazdoor Count</th>
	 	<th>Mazdoor Cost</th>
	 	 
	 	
	 </tr>
	 @foreach ($approved_estimation_details as $approved_estimation_detail)
	 <tr style="color: rgb(87, 92, 92);">
	 	<td>{{ $approved_estimation_detail->id }}</td>
        <td>{{ $approved_estimation_detail->state }}</td>
        <td>{{ $approved_estimation_detail->district }}</td>
        <td>{{ $approved_estimation_detail->city_or_village }}</td>
        <td>{{ $approved_estimation_detail->road_number }}</td>
        <td>{{ $approved_estimation_detail->road_name }}</td>
        <td>{{ $approved_estimation_detail->RoadSize_Length }}</td>
        <td>{{ $approved_estimation_detail->RoadSize_Breadth }}</td>
        <td>{{ $approved_estimation_detail->total_estimation_cost }}</td>
        <td>{{ $approved_estimation_detail->damage_level }}</td>
        <td>{{ $approved_estimation_detail->mazon }}</td>
        <td>{{ $approved_estimation_detail->mazon_cost }}</td>
        <td>{{ $approved_estimation_detail->mazdoor }}</td>
        <td>{{ $approved_estimation_detail->mazdoor_cost }}</td>

     </tr>
     @endforeach
  </table>
  <!--<table>
  	<tr>
  		<th>Id</th>
  		<th>Equipment</th>
  		<th>Equipment Quantity</th>
  		<th>Equipment Cost</th>
  		<th>Road Furnitures</th>
  		<th>Road Furnitures Quantity</th>
  		<th>Road Furnitures Cost</th>
  	</tr>
  	
  		@foreach ($approved_estimation_details as $approved_estimation_detail)
  		<tr>
  		<td> {{ $approved_estimation_detail->id }}</td>
  		
  		@foreach ($approved_estimation_detail->equipment as $equipments)
  		<td> {{ $equipments }}</td><br>
  		@endforeach

  		@foreach ($approved_estimation_detail->equipment_quantity as $equipment_quantity)
  		<td> {{ $equipment_quantity }}</td>
  		@endforeach

  		@foreach ($approved_estimation_detail->equipment_cost as $equipment_cost)
  		<td> {{ $equipment_cost }}</td>
  		@endforeach

  		@foreach ($approved_estimation_detail->roadfurnitures as $roadfurniture)
  		<td> {{ $roadfurniture }}</td>
  		@endforeach

  		@foreach ($approved_estimation_detail->roadfurnitures_quantity as $roadfurnitures_quantity)
  		<td> {{ $roadfurnitures_quantity }}</td>
  		@endforeach

  		@foreach ($approved_estimation_detail->roadfurnitures_cost as $roadfurnitures_cost)
  		<td> {{ $roadfurnitures_cost }}</td>
  		@endforeach
  		</tr>


  		@endforeach
  	
  </table>-->
                      
               
  <footer><hr></footer>
</center>
</body>
</html>